Repository kiraware/paspybin, pull requests merged in 2024-07, with the labels that each got.

#28 update codeql
  .github/workflows/codeql.yml
Labels: enhancement, github_actions

#29 update docs
  .github/workflows/release.yml
  README.md
  docs/how-to-guides.md
  docs/index.md
Labels: documentation, github_actions

#30 fix typo
  docs/index.md
Labels: documentation

#32 Improve docs
  docs/how-to-guides.md
  docs/tutorials.md
  mkdocs.yml
Labels: documentation

#33 Update GitHub workflow
  .github/workflows/dev.yml
  .github/workflows/test.yml
  README.md
  docs/index.md
Labels: github_actions

#34 fix wrong badge link
  README.md
  docs/index.md
Labels: bug, documentation

#36 beautify release workflow
  .github/workflows/release.yml
Labels: github_actions

#37 Add documentation and tests for Non Facade API
  .env.example
  .github/workflows/test.yml
  docs/how-to-guides.md
  docs/tutorials.md
  mkdocs.yml
  src/paspybin/api/paste.py
  src/paspybin/api/pastes.py
  src/paspybin/api/user.py
  tests/test_api/test_paste.py
  tests/test_api/test_pastes.py
  tests/test_api/test_user.py
Labels: documentation, python

#38 update contributing docs
  CONTRIBUTING.md
  docs/how-to-guides.md
Labels: documentation
